CREATE TABLE livros (
ISBN BIGINT PRIMARY KEY  NOT NULL,
NOME VARCHAR(30) NOT NULL,
AUTOR VARCHAR(30) NOT NULL,
EDITORA VARCHAR(30) NOT NULL,
ANO VARCHAR (30) NOT NULL);

CREATE TABLE cliente (
MATRICULA SERIAL PRIMARY KEY  NOT NULL,
NOME VARCHAR(30) NOT NULL,
TELEFONE BIGINT);

CREATE TABLE autor (
ID SERIAL PRIMARY KEY  NOT NULL,
NOME VARCHAR(30) NOT NULL,
PAIS VARCHAR (30) NOT NULL);
