CREATE TABLE livros (
    ISBN BIGINT PRIMARY KEY  NOT NULL,
    NOME VARCHAR(30) NOT NULL,
    AUTOR VARCHAR(30) NOT NULL,
    EDITORA VARCHAR(30) NOT NULL,
    ANO VARCHAR (30) NOT NULL,
    STATUS VARCHAR (30) NOT NULL
);

CREATE TABLE cliente (
    MATRICULA SERIAL PRIMARY KEY  NOT NULL,
    NOME VARCHAR(30) NOT NULL,
    TELEFONE BIGINT
);

CREATE TABLE autor (
    ID SERIAL PRIMARY KEY  NOT NULL,
    NOME VARCHAR(30) NOT NULL,
    PAIS VARCHAR (30) NOT NULL
);

CREATE TABLE emprestimo(
    ID SERIAL PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ISBN BIGINT NOT NULL,
    NOME VARCHAR (30) NOT NULL,
    CLIENTE VARCHAR (30) NOT NULL,
    DATA_RETIRADA DATE NOT NULL,
    DATA_ENTREGA DATE NOT NULL,
);