CREATE TABLE livros (
ISBN SERIAL PRIMARY KEY  NOT NULL,
NOME VARCHAR(30) NOT NULL,
AUTOR SERIAL NOT NULL,
EDITORA VARCHAR(30) NOT NULL,
ANO VARCHAR (30) NOT NULL);

CREATE TABLE cliente (
MATRICULA SERIAL PRIMARY KEY  NOT NULL,
NOME VARCHAR(30) NOT NULL,
TELEFONE INT);

CREATE TABLE autor (
ID SERIAL PRIMARY KEY  NOT NULL,
NOME VARCHAR(30) NOT NULL,
PAIS VARCHAR (30) NOT NULL);
